# Generated by Django 5.2.4 on 2025-07-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Additional credentials for the customer.', null=True),
        ),
    ]
