# Generated by Django 5.2.4 on 2025-08-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_nid_payment_description_payment_entry_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total bill amount for the payment.', max_digits=10),
        ),
    ]
