# Generated by Django 5.2.5 on 2025-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_payment_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Indicates if the customer has a free package.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='secret_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
