# Generated by Django 5.2.4 on 2025-07-26 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('image', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/', verbose_name='Profile_image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('SUPER_ADMIN', 'Super Admin'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
            },
        ),
    ]
